apiVersion: v1
kind: Namespace
metadata:
  name: banking-services
  labels:
    istio-injection: enabled
    banking-environment: local
    security-tier: strict

---
apiVersion: v1
kind: Namespace
metadata:
  name: security
  labels:
    istio-injection: enabled
    banking-environment: local

---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    istio-injection: enabled
    banking-environment: local

