apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

configMapGenerator:
  - name: mesh-params
    envs: [params.env]
    options:
      disableNameSuffixHash: true
      annotations:
        config.kubernetes.io/local-config: "true"

components:
  - ../../components/mesh-params
  - ../../components/platform-params
  - ../../components/corporate-directory
